// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.Data;

#nullable disable

namespace Store.Data.Migrations
{
    [DbContext(typeof(TestDatabaseDbContext))]
    [Migration("20240316175308_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.Data.Entities.Store.StoreEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Identity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identity"));

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("Identity");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("Identity"));

                    b.ToTable("Stores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1e1e197-6306-4426-b0a8-cc09df953e32",
                            Identity = 0,
                            StoreId = "3602aee8-d325-4ca6-8390-395302b09a0f",
                            StoreName = "StoreA"
                        },
                        new
                        {
                            Id = "513f3677-0f9c-44a5-a9db-0439e74c356e",
                            Identity = 0,
                            StoreId = "add1be20-51a3-4a73-bc7b-be9509795ec0",
                            StoreName = "StoreB"
                        },
                        new
                        {
                            Id = "a519ad44-cc1b-4ee6-acda-3509b7786584",
                            Identity = 0,
                            StoreId = "0d3f7b07-d26e-431f-b92c-7e1eeec96900",
                            StoreName = "StoreC"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
